---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: mariadb
  name: mariadb
  namespace: blogs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
      - image: mariadb:latest
        imagePullPolicy: Always
        name: mariadb
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mYPass109
        - name: MYSQL_DATABASE
          value: pressdb
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: mYPass109
        volumeMounts:
        - name: mariadb-data
          mountPath: /mariadb

      volumes:
      - name: mariadb-data
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: blogs
  labels:
    run: mariadb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    run: mariadb
