---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: blogs
  generation: 1
  labels:
    run: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: blog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: blog
    spec:
      containers:
      - image: wordpress:latest
        imagePullPolicy: Always
        name: wordpress
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DATABASE_USER
          value: pressdb
        - name: WORDPRESS_DATABASE_PASSWORD
          value: mYPass109
        - name: WORDPRESS_DB_USERNAME
          value: admin
        - name: WORDPRESS_DB_PASSWORD
          value: mYPass109
        volumeMounts:
        - name: wordpress-data
          mountPath: /wordpress
        - name: apache-data
          mountPath: /apache
        - name: php-data
          mountPath: /php

      volumes:
      - name: wordpress-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
      - name: php-data
        emptyDir: {}

      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: blogs
  name: wordpress
  labels:
    run: blog
spec:
  ports:
  - name: "http"
    protocol: TCP
    port: 80
    targetPort: 80
  - name: "https"
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    run: blog
