apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    This is not the default content for the nginx!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: "server {\r\n    listen       80;\r\n    listen  [::]:80;\r\n    server_name
    \ localhost;\r\n\r\n    location / {\r\n        root   /usr/share/nginx/html;\r\n
    \       index  index.html index.htm;\r\n    }\r\n\r\n    error_page   500 502
    503 504  /50x.html;\r\n    location = /50x.html {\r\n        root   /usr/share/nginx/html;\r\n
    \   }\r\n}"
  other: "This is another value for other key"
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo DB host es $DB_HOST y DB user es $DB_USER > /usr/share/nginx/html/test.html

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-example
  name: nginx-example
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31776
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-example
  name: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-config
          readOnly: true
        - mountPath: /usr/share/nginx/html/
          name: nginx-index
          readOnly: true
        - mountPath: /opt
          name: script-vol
          readOnly: true
        env:
        - name: VAR_EXAMPLE
          value: "A random injected var"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: db_user
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-config
      - configMap:
          defaultMode: 420
          name: nginx-index
        name: nginx-index
      - name: script-vol
        configMap:
          name: nginx-config
          items:
          - key: script
            path: script.sh

